include:
  - component: gitlab.com/PassiveLogic/ci/commitlint@4
  - component: gitlab.com/PassiveLogic/ci/swiftlint@4
  # - component: gitlab.com/PassiveLogic/ci/swiftformat@4
  - component: gitlab.com/PassiveLogic/ci/swift-import-analyzer@4
  - component: gitlab.com/PassiveLogic/ci/swift-build@4
    inputs:
      job-prefix: "amd64-"
      runner-tags:
        - passivelogic-linux-small-amd64
      additional-setup:
        - git submodule sync
        - git submodule update --init
        # Install CUDA
        - apt-get -y install wget
        - wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
        - dpkg -i cuda-keyring_1.1-1_all.deb
        - apt-get update
        - apt-get -y install cuda-nvcc-12-6
  - component: gitlab.com/PassiveLogic/ci/swift-build@4
    inputs:
      job-prefix: "arm64-"
      runner-tags:
        - passivelogic-linux-small-arm64
      additional-setup:
        - git submodule sync
        - git submodule update --init
        # Install CUDA
        - apt-get -y install wget
        - wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/sbsa/cuda-keyring_1.1-1_all.deb
        - dpkg -i cuda-keyring_1.1-1_all.deb
        - apt-get update
        - apt-get -y install cuda-nvcc-12-6

